In [2]:
# Dependencies
import numpy as np

# Python SQL toolkit and Object Relational Mapper
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy import create_engine, func

import numpy as np
import pandas as pd

In [3]:
engine = create_engine("sqlite:///hawaii.sqlite")

# reflect an existing database into a new model
Base = automap_base()
# reflect the tables
Base.prepare(engine, reflect=True)

# Save references to each table
Measurement = Base.classes.measurement
Station = Base.classes.station

In [4]:
# Create our session (link) from Python to the DB
session = Session(engine)

## D1: Determine the Summary Statistics for June

In [5]:
# 1. Import the sqlalchemy extract function.
from sqlalchemy import extract

# 2. Write a query that filters the Measurement table to retrieve the temperatures for the month of June. 

june_q = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date)==6)

In [6]:
#  3. Convert the June temperatures to a list.
june_temps = june_q.all()
june_temps

[('2010-06-01', 78.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 78.0),
 ('2010-06-04', 76.0),
 ('2010-06-05', 77.0),
 ('2010-06-06', 78.0),
 ('2010-06-07', 77.0),
 ('2010-06-08', 78.0),
 ('2010-06-09', 78.0),
 ('2010-06-10', 79.0),
 ('2010-06-11', 78.0),
 ('2010-06-12', 78.0),
 ('2010-06-13', 78.0),
 ('2010-06-14', 77.0),
 ('2010-06-15', 78.0),
 ('2010-06-16', 78.0),
 ('2010-06-17', 77.0),
 ('2010-06-18', 77.0),
 ('2010-06-19', 82.0),
 ('2010-06-20', 78.0),
 ('2010-06-21', 78.0),
 ('2010-06-22', 78.0),
 ('2010-06-23', 78.0),
 ('2010-06-24', 78.0),
 ('2010-06-25', 77.0),
 ('2010-06-26', 76.0),
 ('2010-06-27', 78.0),
 ('2010-06-28', 78.0),
 ('2010-06-29', 78.0),
 ('2010-06-30', 78.0),
 ('2011-06-01', 77.0),
 ('2011-06-02', 78.0),
 ('2011-06-03', 73.0),
 ('2011-06-04', 70.0),
 ('2011-06-05', 76.0),
 ('2011-06-06', 77.0),
 ('2011-06-07', 77.0),
 ('2011-06-08', 77.0),
 ('2011-06-09', 77.0),
 ('2011-06-10', 78.0),
 ('2011-06-11', 77.0),
 ('2011-06-12', 77.0),
 ('2011-06-13', 78.0),
 ('2011-06-14', 78.0),
 ('2011-06-15', 77.0),
 ('2011-06-17', 78.0),
 ('2011-06-18', 78.0),
 ('2011-06-19', 75.0),
 ('2011-06-20', 76.0),
 ('2011-06-21', 76.0),
 ('2011-06-24', 77.0),
 ('2011-06-25', 78.0),
 ('2011-06-26', 76.0),
 ('2011-06-27', 77.0),
 ('2011-06-28', 75.0),
 ('2011-06-29', 77.0),
 ('2012-06-01', 76.0),
 ('2012-06-02', 76.0),
 ('2012-06-03', 75.0),
 ('2012-06-04', 77.0),
 ('2012-06-05', 77.0),
 ('2012-06-06', 76.0),
 ('2012-06-07', 78.0),
 ('2012-06-08', 77.0),
 ('2012-06-09', 76.0),
 ('2012-06-10', 77.0),
 ('2012-06-11', 76.0),
 ('2012-06-12', 76.0),
 ('2012-06-13', 77.0),
 ('2012-06-14', 77.0),
 ('2012-06-15', 78.0),
 ('2012-06-16', 77.0),
 ('2012-06-17', 77.0),
 ('2012-06-18', 77.0),
 ('2012-06-19', 76.0),
 ('2012-06-20', 75.0),
 ('2012-06-21', 76.0),
 ('2012-06-22', 76.0),
 ('2012-06-23', 77.0),
 ('2012-06-24', 76.0),
 ('2012-06-25', 73.0),
 ('2012-06-26', 73.0),
 ('2012-06-27', 75.0),
 ('2012-06-28', 77.0),
 ('2012-06-29', 76.0),
 ('2012-06-30', 77.0),
 ('2013-06-01', 79.0),
 ('2013-06-02', 78.0),
 ('2013-06-03', 79.0),
 ('2013-06-04', 78.0),
 ('2013-06-05', 78.0),
 ('2013-06-06', 79.0),
 ('2013-06-07', 77.0),
 ('2013-06-08', 77.0),
 ('2013-06-09', 77.0),
 ('2013-06-10', 77.0),
 ('2013-06-11', 77.0),
 ('2013-06-12', 78.0),
 ('2013-06-13', 77.0),
 ('2013-06-14', 76.0),
 ('2013-06-15', 78.0),
 ('2013-06-16', 78.0),
 ('2013-06-17', 77.0),
 ('2013-06-18', 78.0),
 ('2013-06-19', 78.0),
 ('2013-06-20', 73.0),
 ('2013-06-21', 76.0),
 ('2013-06-22', 77.0),
 ('2013-06-23', 75.0),
 ('2013-06-24', 76.0),
 ('2013-06-25', 74.0),
 ('2013-06-26', 75.0),
 ('2013-06-27', 77.0),
 ('2013-06-28', 76.0),
 ('2013-06-29', 77.0),
 ('2013-06-30', 78.0),
 ('2014-06-01', 79.0),
 ('2014-06-02', 77.0),
 ('2014-06-03', 78.0),
 ('2014-06-04', 79.0),
 ('2014-06-05', 78.0),
 ('2014-06-06', 78.0),
 ('2014-06-07', 78.0),
 ('2014-06-08', 78.0),
 ('2014-06-09', 79.0),
 ('2014-06-10', 79.0),
 ('2014-06-11', 82.0),
 ('2014-06-12', 80.0),
 ('2014-06-13', 79.0),
 ('2014-06-14', 79.0),
 ('2014-06-15', 78.0),
 ('2014-06-16', 78.0),
 ('2014-06-17', 77.0),
 ('2014-06-18', 78.0),
 ('2014-06-19', 78.0),
 ('2014-06-20', 73.0),
 ('2014-06-21', 75.0),
 ('2014-06-22', 75.0),
 ('2014-06-23', 76.0),
 ('2014-06-24', 84.0),
 ('2014-06-25', 79.0),
 ('2014-06-26', 76.0),
 ('2014-06-27', 79.0),
 ('2014-06-28', 79.0),
 ('2014-06-29', 77.0),
 ('2014-06-30', 79.0),
 ('2015-06-01', 78.0),
 ('2015-06-02', 78.0),
 ('2015-06-03', 79.0),
 ('2015-06-04', 77.0),
 ('2015-06-05', 79.0),
 ('2015-06-06', 78.0),
 ('2015-06-07', 78.0),
 ('2015-06-08', 78.0),
 ('2015-06-09', 79.0),
 ('2015-06-10', 77.0),
 ('2015-06-11', 78.0),
 ('2015-06-12', 78.0),
 ('2015-06-13', 78.0),
 ('2015-06-14', 78.0),
 ('2015-06-15', 79.0),
 ('2015-06-16', 79.0),
 ('2015-06-17', 77.0),
 ('2015-06-18', 78.0),
 ('2015-06-19', 78.0),
 ('2015-06-20', 78.0),
 ('2015-06-21', 79.0),
 ('2015-06-22', 79.0),
 ('2015-06-23', 77.0),
 ('2015-06-24', 79.0),
 ('2015-06-25', 79.0),
 ('2015-06-26', 79.0),
 ('2015-06-27', 81.0),
 ('2015-06-28', 76.0),
 ('2015-06-29', 80.0),
 ('2015-06-30', 78.0),
 ('2016-06-01', 76.0),
 ('2016-06-02', 71.0),
 ('2016-06-03', 71.0),
 ('2016-06-04', 74.0),
 ('2016-06-05', 76.0),
 ('2016-06-06', 78.0),
 ('2016-06-07', 77.0),
 ('2016-06-08', 77.0),
 ('2016-06-09', 73.0),
 ('2016-06-10', 77.0),
 ('2016-06-11', 78.0),
 ('2016-06-12', 78.0),
 ('2016-06-13', 80.0),
 ('2016-06-14', 79.0),
 ('2016-06-15', 78.0),
 ('2016-06-16', 77.0),
 ('2016-06-17', 76.0),
 ('2016-06-18', 77.0),
 ('2016-06-19', 77.0),
 ('2016-06-20', 78.0),
 ('2016-06-21', 80.0),
 ('2016-06-22', 79.0),
 ('2016-06-23', 79.0),
 ('2016-06-24', 77.0),
 ('2016-06-25', 78.0),
 ('2016-06-26', 79.0),
 ('2016-06-27', 80.0),
 ('2016-06-28', 76.0),
 ('2016-06-29', 79.0),
 ('2016-06-30', 80.0),
 ('2017-06-01', 79.0),
 ('2017-06-02', 79.0),
 ('2017-06-03', 79.0),
 ('2017-06-04', 79.0),
 ('2017-06-05', 80.0),
 ('2017-06-06', 79.0),
 ('2017-06-07', 79.0),
 ('2017-06-08', 80.0),
 ('2017-06-09', 80.0),
 ('2017-06-10', 77.0),
 ('2017-06-11', 79.0),
 ('2017-06-12', 83.0),
 ('2017-06-13', 80.0),
 ('2017-06-14', 80.0),
 ('2017-06-15', 78.0),
 ('2017-06-16', 79.0),
 ('2017-06-17', 80.0),
 ('2017-06-18', 77.0),
 ('2017-06-19', 80.0),
 ('2017-06-20', 78.0),
 ('2017-06-21', 79.0),
 ('2017-06-22', 80.0),
 ('2017-06-23', 78.0),
 ('2017-06-24', 80.0),
 ('2017-06-25', 80.0),
 ('2017-06-26', 81.0),
 ('2017-06-27', 80.0),
 ('2017-06-28', 79.0),
 ('2017-06-29', 79.0),
 ('2017-06-30', 75.0),
 ('2010-06-01', 74.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 75.0),
 ('2010-06-04', 75.0),
 ('2010-06-05', 74.0),
 ('2010-06-06', 75.0),
 ('2010-06-07', 75.0),
 ('2010-06-08', 75.0),
 ('2010-06-09', 75.0),
 ('2010-06-10', 75.0),
 ('2010-06-11', 83.0),
 ('2010-06-12', 75.0),
 ('2010-06-13', 76.0),
 ('2010-06-14', 73.0),
 ('2010-06-15', 74.0),
 ('2010-06-16', 74.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 70.0),
 ('2010-06-19', 74.0),
 ('2010-06-20', 75.0),
 ('2010-06-21', 75.0),
 ('2010-06-22', 75.0),
 ('2010-06-23', 75.0),
 ('2010-06-24', 75.0),
 ('2010-06-25', 74.0),
 ('2010-06-26', 72.0),
 ('2010-06-27', 76.0),
 ('2010-06-28', 73.0),
 ('2010-06-29', 75.0),
 ('2010-06-30', 76.0),
 ('2011-06-01', 74.0),
 ('2011-06-02', 75.0),
 ('2011-06-03', 71.0),
 ('2011-06-04', 69.0),
 ('2011-06-05', 69.0),
 ('2011-06-06', 74.0),
 ('2011-06-07', 71.0),
 ('2011-06-08', 74.0),
 ('2011-06-09', 74.0),
 ('2011-06-10', 75.0),
 ('2011-06-11', 73.0),
 ('2011-06-12', 73.0),
 ('2011-06-13', 73.0),
 ('2011-06-14', 75.0),
 ('2011-06-15', 75.0),
 ('2011-06-16', 74.0),
 ('2011-06-17', 74.0),
 ('2011-06-18', 75.0),
 ('2011-06-19', 74.0),
 ('2011-06-20', 73.0),
 ('2011-06-21', 72.0),
 ('2011-06-22', 74.0),
 ('2011-06-23', 72.0),
 ('2011-06-24', 75.0),
 ('2011-06-25', 76.0),
 ('2011-06-26', 74.0),
 ('2011-06-27', 74.0),
 ('2011-06-28', 74.0),
 ('2011-06-29', 74.0),
 ('2011-06-30', 74.0),
 ('2012-06-01', 71.0),
 ('2012-06-02', 71.0),
 ('2012-06-03', 75.0),
 ('2012-06-04', 72.0),
 ('2012-06-05', 72.0),
 ('2012-06-06', 73.0),
 ('2012-06-07', 73.0),
 ('2012-06-08', 73.0),
 ('2012-06-09', 74.0),
 ('2012-06-10', 73.0),
 ('2012-06-11', 72.0),
 ('2012-06-12', 72.0),
 ('2012-06-13', 70.0),
 ('2012-06-14', 72.0),
 ('2012-06-15', 72.0),
 ('2012-06-16', 72.0),
 ('2012-06-17', 74.0),
 ('2012-06-18', 73.0),
 ('2012-06-19', 73.0),
 ('2012-06-20', 70.0),
 ('2012-06-21', 73.0),
 ('2012-06-22', 72.0),
 ('2012-06-23', 73.0),
 ('2012-06-24', 69.0),
 ('2012-06-25', 72.0),
 ('2012-06-26', 71.0),
 ('2012-06-27', 71.0),
 ('2012-06-28', 73.0),
 ('2012-06-29', 73.0),
 ('2012-06-30', 72.0),
 ('2013-06-01', 75.0),
 ('2013-06-02', 75.0),
 ('2013-06-03', 75.0),
 ('2013-06-04', 75.0),
 ('2013-06-05', 74.0),
 ('2013-06-06', 74.0),
 ('2013-06-07', 74.0),
 ('2013-06-08', 75.0),
 ('2013-06-09', 75.0),
 ('2013-06-10', 74.0),
 ('2013-06-11', 75.0),
 ('2013-06-12', 75.0),
 ('2013-06-13', 74.0),
 ('2013-06-14', 72.0),
 ('2013-06-15', 74.0),
 ('2013-06-16', 74.0),
 ('2013-06-17', 74.0),
 ('2013-06-18', 74.0),
 ('2013-06-19', 74.0),
 ('2013-06-20', 72.0),
 ('2013-06-21', 70.0),
 ('2013-06-22', 75.0),
 ('2013-06-23', 74.0),
 ('2013-06-24', 71.0),
 ('2013-06-25', 71.0),
 ('2013-06-26', 70.0),
 ('2013-06-27', 73.0),
 ('2013-06-28', 71.0),
 ('2013-06-29', 71.0),
 ('2013-06-30', 77.0),
 ('2014-06-01', 77.0),
 ('2014-06-02', 74.0),
 ('2014-06-03', 73.0),
 ('2014-06-04', 75.0),
 ('2014-06-05', 75.0),
 ('2014-06-06', 74.0),
 ('2014-06-07', 74.0),
 ('2014-06-08', 75.0),
 ('2014-06-09', 75.0),
 ('2014-06-10', 72.0),
 ('2014-06-11', 74.0),
 ('2014-06-12', 76.0),
 ('2014-06-13', 76.0),
 ('2014-06-14', 75.0),
 ('2014-06-15', 75.0),
 ('2014-06-16', 74.0),
 ('2014-06-17', 72.0),
 ('2014-06-18', 74.0),
 ('2014-06-19', 75.0),
 ('2014-06-20', 70.0),
 ('2014-06-21', 71.0),
 ('2014-06-22', 72.0),
 ('2014-06-23', 71.0),
 ('2014-06-24', 73.0),
 ('2014-06-25', 74.0),
 ('2014-06-26', 72.0),
 ('2014-06-27', 74.0),
 ('2014-06-28', 76.0),
 ('2014-06-29', 72.0),
 ('2014-06-30', 75.0),
 ('2015-06-03', 75.0),
 ('2015-06-04', 72.0),
 ('2015-06-05', 70.0),
 ('2015-06-06', 76.0),
 ('2015-06-07', 78.0),
 ('2015-06-08', 72.0),
 ('2015-06-09', 74.0),
 ('2015-06-10', 74.0),
 ('2015-06-11', 72.0),
 ('2015-06-12', 71.0),
 ('2015-06-13', 79.0),
 ('2015-06-14', 79.0),
 ('2015-06-15', 76.0),
 ('2015-06-16', 75.0),
 ('2015-06-17', 72.0),
 ('2015-06-18', 74.0),
 ('2015-06-19', 76.0),
 ('2015-06-20', 76.0),
 ('2015-06-21', 77.0),
 ('2015-06-22', 75.0),
 ('2015-06-23', 76.0),
 ('2015-06-24', 75.0),
 ('2015-06-25', 75.0),
 ('2015-06-26', 76.0),
 ('2015-06-27', 76.0),
 ('2015-06-29', 74.0),
 ('2016-06-01', 70.0),
 ('2016-06-02', 69.0),
 ('2016-06-03', 70.0),
 ('2016-06-04', 68.0),
 ('2016-06-05', 70.0),
 ('2016-06-06', 74.0),
 ('2016-06-07', 75.0),
 ('2016-06-08', 74.0),
 ('2016-06-09', 71.0),
 ('2016-06-10', 73.0),
 ('2016-06-11', 75.0),
 ('2016-06-12', 74.0),
 ('2016-06-13', 76.0),
 ('2016-06-14', 76.0),
 ('2016-06-15', 76.0),
 ('2016-06-16', 76.0),
 ('2016-06-17', 75.0),
 ('2016-06-18', 75.0),
 ('2016-06-19', 75.0),
 ('2016-06-20', 74.0),
 ('2016-06-21', 73.0),
 ('2016-06-22', 76.0),
 ('2016-06-23', 74.0),
 ('2016-06-24', 78.0),
 ('2016-06-25', 71.0),
 ('2016-06-26', 75.0),
 ('2016-06-27', 75.0),
 ('2016-06-28', 74.0),
 ('2016-06-29', 77.0),
 ('2016-06-30', 77.0),
 ('2017-06-01', 76.0),
 ('2017-06-02', 76.0),
 ('2017-06-03', 76.0),
 ('2017-06-04', 78.0),
 ('2017-06-05', 76.0),
 ('2017-06-06', 75.0),
 ('2017-06-07', 75.0),
 ('2017-06-08', 76.0),
 ('2017-06-09', 78.0),
 ('2017-06-10', 75.0),
 ('2017-06-11', 73.0),
 ('2017-06-12', 76.0),
 ('2017-06-13', 76.0),
 ('2017-06-14', 76.0),
 ('2017-06-15', 77.0),
 ('2017-06-16', 76.0),
 ('2017-06-17', 77.0),
 ('2017-06-18', 72.0),
 ('2017-06-19', 77.0),
 ('2017-06-20', 75.0),
 ('2017-06-21', 82.0),
 ('2017-06-22', 77.0),
 ('2017-06-23', 76.0),
 ('2017-06-24', 74.0),
 ('2017-06-25', 73.0),
 ('2017-06-26', 77.0),
 ('2017-06-27', 77.0),
 ('2017-06-28', 77.0),
 ('2017-06-29', 76.0),
 ('2017-06-30', 74.0),
 ('2010-06-01', 73.0),
 ('2010-06-02', 72.0),
 ('2010-06-03', 74.0),
 ('2010-06-04', 73.0),
 ('2010-06-05', 72.0),
 ('2010-06-06', 75.0),
 ('2010-06-07', 74.0),
 ('2010-06-08', 75.0),
 ('2010-06-09', 73.0),
 ('2010-06-10', 75.0),
 ('2010-06-11', 76.0),
 ('2010-06-12', 74.0),
 ('2010-06-13', 74.0),
 ('2010-06-14', 73.0),
 ('2010-06-15', 73.0),
 ('2010-06-16', 76.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 70.0),
 ('2010-06-19', 75.0),
 ('2010-06-20', 73.0),
 ('2010-06-21', 74.0),
 ('2010-06-22', 74.0),
 ('2010-06-23', 74.0),
 ('2010-06-24', 74.0),
 ('2010-06-25', 70.0),
 ('2010-06-27', 75.0),
 ('2010-06-28', 74.0),
 ('2010-06-29', 73.0),
 ('2010-06-30', 74.0),
 ('2011-06-01', 72.0),
 ('2011-06-02', 73.0),
 ('2011-06-03', 67.0),
 ('2011-06-04', 69.0),
 ('2011-06-05', 76.0),
 ('2011-06-06', 73.0),
 ('2011-06-07', 70.0),
 ('2011-06-08', 72.0),
 ('2011-06-09', 74.0),
 ('2011-06-10', 72.0),
 ('2011-06-13', 72.0),
 ('2011-06-14', 75.0),
 ('2011-06-15', 73.0),
 ('2011-06-16', 73.0),
 ('2011-06-17', 72.0),
 ('2011-06-18', 74.0),
 ('2011-06-19', 76.0),
 ('2011-06-21', 72.0),
 ('2011-06-22', 74.0),
 ('2011-06-23', 70.0),
 ('2011-06-24', 74.0),
 ('2011-06-25', 74.0),
 ('2011-06-27', 74.0),
 ('2011-06-28', 71.0),
 ('2012-06-21', 75.0),
 ('2012-06-22', 75.0),
 ('2012-06-24', 76.0),
 ('2012-06-25', 77.0),
 ('2012-06-26', 75.0),
 ('2012-06-27', 74.0),
 ('2012-06-28', 75.0),
 ('2012-06-29', 76.0),
 ('2012-06-30', 78.0),
 ('2013-06-03', 78.0),
 ('2013-06-04', 76.0),
 ('2013-06-05', 78.0),
 ('2013-06-06', 76.0),
 ('2013-06-07', 76.0),
 ('2013-06-08', 78.0),
 ('2013-06-09', 79.0),
 ('2013-06-10', 77.0),
 ('2013-06-11', 76.0),
 ('2013-06-12', 77.0),
 ('2013-06-13', 77.0),
 ('2013-06-14', 76.0),
 ('2013-06-16', 78.0),
 ('2013-06-17', 76.0),
 ('2013-06-18', 76.0),
 ('2013-06-19', 77.0),
 ('2013-06-20', 71.0),
 ('2013-06-25', 74.0),
 ('2013-06-26', 72.0),
 ('2013-06-27', 77.0),
 ('2014-06-01', 77.0),
 ('2014-06-02', 78.0),
 ('2014-06-03', 77.0),
 ('2014-06-04', 77.0),
 ('2014-06-05', 76.0),
 ('2014-06-06', 75.0),
 ('2014-06-07', 79.0),
 ('2014-06-09', 75.0),
 ('2014-06-10', 73.0),
 ('2014-06-11', 76.0),
 ('2014-06-12', 78.0),
 ('2014-06-13', 77.0),
 ('2014-06-14', 78.0),
 ('2014-06-16', 76.0),
 ('2014-06-17', 75.0),
 ('2014-06-18', 76.0),
 ('2014-06-19', 77.0),
 ('2014-06-20', 74.0),
 ('2014-06-21', 78.0),
 ('2014-06-23', 77.0),
 ('2014-06-24', 77.0),
 ('2014-06-25', 74.0),
 ('2014-06-26', 74.0),
 ('2014-06-27', 78.0),
 ('2014-06-29', 79.0),
 ('2014-06-30', 79.0),
 ('2015-06-01', 78.0),
 ('2015-06-03', 75.0),
 ('2015-06-04', 76.0),
 ('2015-06-05', 78.0),
 ('2015-06-06', 78.0),
 ('2015-06-08', 74.0),
 ('2015-06-09', 78.0),
 ('2015-06-10', 77.0),
 ('2015-06-11', 76.0),
 ('2015-06-12', 78.0),
 ('2015-06-14', 78.0),
 ('2015-06-15', 78.0),
 ('2015-06-16', 78.0),
 ('2015-06-17', 74.0),
 ('2015-06-18', 79.0),
 ('2015-06-19', 77.0),
 ('2015-06-20', 73.0),
 ('2015-06-21', 79.0),
 ('2015-06-22', 79.0),
 ('2015-06-23', 78.0),
 ('2015-06-24', 77.0),
 ('2015-06-25', 78.0),
 ('2015-06-26', 78.0),
 ('2015-06-27', 80.0),
 ('2015-06-28', 80.0),
 ('2015-06-29', 79.0),
 ('2015-06-30', 74.0),
 ('2016-06-01', 71.0),
 ('2016-06-02', 74.0),
 ('2016-06-03', 75.0),
 ('2016-06-07', 75.0),
 ('2016-06-08', 74.0),
 ('2016-06-09', 76.0),
 ('2016-06-10', 75.0),
 ('2016-06-11', 77.0),
 ('2016-06-12', 77.0),
 ('2016-06-13', 79.0),
 ('2016-06-14', 79.0),
 ('2016-06-15', 78.0),
 ('2016-06-16', 79.0),
 ('2016-06-17', 73.0),
 ('2016-06-18', 78.0),
 ('2016-06-19', 79.0),
 ('2016-06-20', 80.0),
 ('2016-06-21', 76.0),
 ('2016-06-22', 79.0),
 ('2016-06-23', 79.0),
 ('2016-06-24', 77.0),
 ('2016-06-25', 80.0),
 ('2016-06-26', 79.0),
 ('2016-06-27', 78.0),
 ('2016-06-28', 78.0),
 ('2016-06-29', 79.0),
 ('2016-06-30', 78.0),
 ('2017-06-01', 81.0),
 ('2017-06-02', 78.0),
 ('2017-06-03', 80.0),
 ('2017-06-04', 79.0),
 ('2017-06-05', 81.0),
 ('2017-06-06', 80.0),
 ('2017-06-07', 81.0),
 ('2017-06-08', 79.0),
 ('2017-06-09', 81.0),
 ('2017-06-10', 78.0),
 ('2017-06-11', 79.0),
 ('2017-06-12', 79.0),
 ('2017-06-13', 75.0),
 ('2017-06-14', 79.0),
 ('2017-06-15', 78.0),
 ('2017-06-16', 80.0),
 ('2017-06-17', 78.0),
 ('2017-06-18', 77.0),
 ('2017-06-19', 78.0),
 ('2017-06-20', 79.0),
 ('2017-06-23', 76.0),
 ('2017-06-26', 80.0),
 ('2017-06-29', 76.0),
 ('2017-06-30', 81.0),
 ('2010-06-01', 77.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 77.0),
 ('2010-06-04', 75.0),
 ('2010-06-07', 76.0),
 ('2010-06-08', 79.0),
 ('2010-06-09', 79.0),
 ('2010-06-10', 77.0),
 ('2010-06-15', 76.0),
 ('2010-06-16', 77.0),
 ('2010-06-17', 76.0),
 ('2010-06-18', 73.0),
 ('2010-06-21', 76.0),
 ('2010-06-22', 77.0),
 ('2010-06-23', 77.0),
 ('2010-06-24', 78.0),
 ('2010-06-25', 77.0),
 ('2010-06-28', 76.0),
 ('2010-06-29', 78.0),
 ('2010-06-30', 78.0),
 ('2011-06-01', 75.0),
 ('2011-06-02', 77.0),
 ('2011-06-03', 65.0),
 ('2011-06-06', 76.0),
 ('2011-06-07', 74.0),
 ('2011-06-08', 76.0),
 ('2011-06-09', 76.0),
 ('2011-06-13', 77.0),
 ('2011-06-14', 77.0),
 ('2011-06-15', 76.0),
 ('2011-06-16', 77.0),
 ('2011-06-17', 76.0),
 ('2011-06-20', 77.0),
 ('2011-06-21', 74.0),
 ('2011-06-22', 76.0),
 ('2011-06-23', 73.0),
 ('2011-06-24', 75.0),
 ('2011-06-27', 76.0),
 ('2011-06-28', 75.0),
 ('2011-06-29', 76.0),
 ('2011-06-30', 75.0),
 ('2012-06-01', 74.0),
 ('2012-06-04', 74.0),
 ('2012-06-05', 74.0),
 ('2012-06-06', 74.0),
 ('2012-06-07', 76.0),
 ('2012-06-08', 76.0),
 ('2012-06-12', 77.0),
 ('2012-06-13', 77.0),
 ('2012-06-14', 78.0),
 ('2012-06-15', 73.0),
 ('2012-06-18', 75.0),
 ('2012-06-19', 72.0),
 ('2012-06-20', 76.0),
 ('2012-06-21', 76.0),
 ('2012-06-22', 73.0),
 ('2012-06-25', 74.0),
 ('2012-06-26', 72.0),
 ('2012-06-27', 76.0),
 ('2012-06-28', 76.0),
 ('2012-06-29', 76.0),
 ('2013-06-03', 78.0),
 ('2013-06-04', 78.0),
 ('2013-06-05', 78.0),
 ('2013-06-06', 78.0),
 ('2013-06-07', 75.0),
 ('2013-06-10', 77.0),
 ('2013-06-12', 73.0),
 ('2013-06-13', 78.0),
 ('2013-06-14', 75.0),
 ('2013-06-17', 73.0),
 ('2013-06-18', 77.0),
 ('2013-06-19', 80.0),
 ('2013-06-20', 70.0),
 ('2013-06-21', 78.0),
 ('2013-06-25', 72.0),
 ('2013-06-26', 78.0),
 ('2013-06-27', 72.0),
 ('2013-06-28', 78.0),
 ('2014-06-02', 77.0),
 ('2014-06-03', 79.0),
 ('2014-06-04', 77.0),
 ('2014-06-05', 78.0),
 ('2014-06-06', 74.0),
 ('2014-06-09', 79.0),
 ('2014-06-10', 79.0),
 ('2014-06-12', 79.0),
 ('2014-06-13', 79.0),
 ('2014-06-16', 77.0),
 ('2014-06-17', 79.0),
 ('2014-06-18', 78.0),
 ('2014-06-19', 80.0),
 ('2014-06-20', 81.0),
 ('2014-06-27', 81.0),
 ('2015-06-10', 78.0),
 ('2015-06-12', 77.0),
 ('2015-06-15', 78.0),
 ('2015-06-16', 79.0),
 ('2015-06-17', 77.0),
 ('2015-06-18', 79.0),
 ('2015-06-19', 80.0),
 ('2015-06-22', 79.0),
 ('2015-06-23', 78.0),
 ('2015-06-24', 79.0),
 ('2015-06-25', 79.0),
 ('2015-06-29', 79.0),
 ('2015-06-30', 81.0),
 ('2016-06-01', 64.0),
 ('2016-06-02', 65.0),
 ('2016-06-03', 75.0),
 ('2016-06-06', 76.0),
 ('2016-06-07', 78.0),
 ('2016-06-08', 77.0),
 ('2016-06-09', 75.0),
 ('2016-06-13', 78.0),
 ('2016-06-14', 81.0),
 ('2016-06-15', 78.0),
 ('2016-06-16', 76.0),
 ('2016-06-17', 73.0),
 ('2016-06-20', 74.0),
 ('2016-06-21', 76.0),
 ('2016-06-22', 78.0),
 ('2016-06-23', 79.0),
 ('2016-06-24', 78.0),
 ('2016-06-27', 72.0),
 ('2016-06-28', 78.0),
 ('2016-06-29', 80.0),
 ('2016-06-30', 81.0),
 ('2017-06-02', 79.0),
 ('2017-06-05', 78.0),
 ('2017-06-06', 80.0),
 ('2017-06-07', 80.0),
 ('2017-06-08', 78.0),
 ('2017-06-09', 80.0),
 ('2017-06-13', 81.0),
 ('2017-06-14', 78.0),
 ('2017-06-15', 77.0),
 ('2017-06-16', 78.0),
 ('2017-06-19', 78.0),
 ('2017-06-20', 77.0),
 ('2017-06-21', 76.0),
 ('2017-06-22', 81.0),
 ('2017-06-23', 76.0),
 ('2017-06-26', 82.0),
 ('2017-06-27', 80.0),
 ('2017-06-28', 80.0),
 ('2017-06-29', 79.0),
 ('2017-06-30', 74.0),
 ('2010-06-01', 69.0),
 ('2010-06-02', 70.0),
 ('2010-06-03', 67.0),
 ('2010-06-04', 70.0),
 ('2010-06-05', 73.0),
 ('2010-06-06', 73.0),
 ('2010-06-09', 72.0),
 ('2010-06-10', 72.0),
 ('2010-06-11', 77.0),
 ('2010-06-12', 70.0),
 ('2010-06-13', 78.0),
 ('2010-06-15', 73.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 70.0),
 ('2010-06-19', 74.0),
 ('2010-06-20', 77.0),
 ('2010-06-22', 69.0),
 ('2010-06-23', 73.0),
 ('2010-06-24', 73.0),
 ('2010-06-25', 74.0),
 ('2010-06-28', 73.0),
 ('2010-06-29', 72.0),
 ('2010-06-30', 75.0),
 ('2011-06-08', 73.0),
 ('2011-06-09', 76.0),
 ('2011-06-12', 74.0),
 ('2011-06-13', 76.0),
 ('2011-06-14', 73.0),
 ('2011-06-15', 76.0),
 ('2011-06-16', 76.0),
 ('2011-06-20', 78.0),
 ('2011-06-21', 75.0),
 ('2011-06-22', 77.0),
 ('2012-06-01', 75.0),
 ('2012-06-14', 73.0),
 ('2012-06-21', 76.0),
 ('2012-06-26', 71.0),
 ('2012-06-29', 71.0),
 ('2010-06-01', 76.0),
 ('2010-06-02', 76.0),
 ('2010-06-03', 76.0),
 ('2010-06-04', 73.0),
 ('2010-06-05', 78.0),
 ('2010-06-06', 77.0),
 ('2010-06-07', 77.0),
 ('2010-06-08', 77.0),
 ('2010-06-09', 78.0),
 ('2010-06-10', 78.0),
 ('2010-06-11', 76.0),
 ('2010-06-12', 76.0),
 ('2010-06-13', 79.0),
 ('2010-06-14', 74.0),
 ('2010-06-15', 75.0),
 ('2010-06-16', 76.0),
 ('2010-06-17', 75.0),
 ('2010-06-18', 73.0),
 ('2010-06-19', 76.0),
 ('2010-06-20', 78.0),
 ('2010-06-21', 76.0),
 ('2010-06-22', 79.0),
 ('2010-06-23', 77.0),
 ('2010-06-24', 76.0),
 ('2010-06-25', 74.0),

In [37]:
# 4. Create a DataFrame from the list of temperatures for the month of June. 
june_temp_df = pd.DataFrame(june_temps, columns=['date','June, ℉'])
june_temp_df.set_index('date', inplace=True)
june_temp_df.head()

            June, ℉
date
2010-06-01     78.0
2010-06-02     76.0
2010-06-03     78.0
2010-06-04     76.0
2010-06-05     77.0

In [38]:
# 5. Calculate and print out the summary statistics for the June temperature DataFrame.
june_temp_df.describe()

           June, ℉
count  1700.000000
mean     74.944118
std       3.257417
min      64.000000
25%      73.000000
50%      75.000000
75%      77.000000
max      85.000000

## D2: Determine the Summary Statistics for December

In [9]:
# 6. Write a query that filters the Measurement table to retrieve the temperatures for the month of December.

december_q = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date)==12)

In [10]:
# 7. Convert the December temperatures to a list.
december_temps = december_q.all()

In [35]:
# 8. Create a DataFrame from the list of temperatures for the month of December. 
december_temp_df = pd.DataFrame(december_temps, columns=['date','December, ℉'])
december_temp_df.set_index('date', inplace=True)
december_temp_df.head()

            December, ℉
date
2010-12-01         76.0
2010-12-03         74.0
2010-12-04         74.0
2010-12-06         64.0
2010-12-07         64.0

In [36]:
# 9. Calculate and print out the summary statistics for the Decemeber temperature DataFrame.
december_temp_df.describe()

       December, ℉
count  1517.000000
mean     71.041529
std       3.745920
min      56.000000
25%      69.000000
50%      71.000000
75%      74.000000
max      83.000000

# Additional queries for deliverable 3

In [26]:
december_prcp = session.query(Measurement.date, Measurement.prcp).filter(extract('month', Measurement.date)==12).all()
december_prcp_df = pd.DataFrame(december_prcp, columns=['date','precipitation in December'])
december_prcp_df.set_index('date', inplace=True)
december_prcp_df.describe()

       precipitation in December
count                1405.000000
mean                    0.216819
std                     0.541399
min                     0.000000
25%                     0.000000
50%                     0.030000
75%                     0.150000
max                     6.420000

In [27]:
june_prcp = session.query(Measurement.date, Measurement.prcp).filter(extract('month', Measurement.date)==6).all()
june_prcp_df = pd.DataFrame(june_prcp, columns=['date','precipitation in June'])
june_prcp_df.set_index('date', inplace=True)
june_prcp_df.describe()

       precipitation in June
count            1574.000000
mean                0.136360
std                 0.335731
min                 0.000000
25%                 0.000000
50%                 0.020000
75%                 0.120000
max                 4.430000

In [34]:
march_temp = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date)==3).all()
march_temp_df = pd.DataFrame(march_temp, columns=['date','March, ℉'])
march_temp_df.set_index('date', inplace=True)
march_temp_df.describe()

          March, ℉
count  1693.000000
mean     70.059067
std       3.845271
min      56.000000
25%      68.000000
50%      70.000000
75%      73.000000
max      82.000000

In [33]:
september_temp = session.query(Measurement.date, Measurement.tobs).filter(extract('month', Measurement.date)==9).all()
september_temp_df = pd.DataFrame(september_temp, columns=['date','Septemper,℉'])
september_temp_df.set_index('date', inplace=True)
september_temp_df.describe()

       Septemper,℉
count  1480.000000
mean     76.164865
std       3.535178
min      64.000000
25%      74.000000
50%      76.000000
75%      79.000000
max      87.000000